version: 2
jobs:
  build:
    docker:
      - image: greyltc/archlinux
    steps:
      - checkout
      - run:
          name: Install required packages
          command: pacman -Sy --noconfirm clang make cmake openssl-1.0 gnutls z git systemd ninja
      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Prepare environment
          command: pacman -Qi openssl-1.0 && mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j4
