version: 2
jobs:
  build:
    docker:
      - image: greyltc/archlinux
    steps:
      - checkout
      - run:
          name: Install required packages
          command: pacman -Sy --noconfirm clang make cmake openssl-1.0 gnutls z git ninja systemd-libs
      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Prepare environment
          command: |
            mkdir build
      - run:
          name: Build
          command: |
            cd build
            cmake -DENABLE_MOCK=1 ..
            make -j4
      - run:
          name: Test
          command: |
            cd build
            ./DaemonTests
